# Generated by Django 4.2.13 on 2024-12-28 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('abbr', models.CharField(max_length=10, unique=True)),
                ('member_number', models.IntegerField()),
            ],
            options={
                'db_table': 'association',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('abbr', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=8)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('postal_address', models.CharField(max_length=45)),
                ('photo', models.ImageField(unique=True, upload_to='img')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_association', to='asapcutapp.association')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_position', to='asapcutapp.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_logs',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.BigIntegerField()),
                ('requested_amount', models.BigIntegerField()),
                ('payment_date', models.DateField()),
                ('amount_paid', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('arrears_amount', models.BigIntegerField(default=0)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_association', to='asapcutapp.association')),
            ],
            options={
                'db_table': 'contribution',
            },
        ),
        migrations.AddField(
            model_name='association',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_university', to='asapcutapp.university'),
        ),
    ]
