# Generated by Django 4.2.13 on 2024-12-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapcutapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='logo',
            field=models.ImageField(default='asso.jpg', upload_to='association_logos'),
        ),
    ]
