# Generated by Django 4.2.13 on 2024-12-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asapcutapp', '0002_association_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='arrears_amount',
        ),
        migrations.CreateModel(
            name='Arrears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrears_amount', models.BigIntegerField(default=0)),
                ('year', models.DateField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_arrears', to='asapcutapp.association')),
            ],
            options={
                'db_table': 'arrears',
            },
        ),
    ]
