# Generated by Django 4.2.13 on 2024-12-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asapcutapp', '0003_remove_contribution_arrears_amount_arrears'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arrears',
            table='arrear',
        ),
    ]
