# Generated by Django 4.2.13 on 2024-12-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asapcutapp', '0004_alter_arrears_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('abbr', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'level',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_level', to='asapcutapp.level'),
        ),
    ]
