# Generated by Django 4.1.13 on 2025-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapcutapp', '0006_alter_university_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='year',
            field=models.CharField(default='2024-2025', max_length=9),
        ),
    ]
