# Generated by Django 4.1.13 on 2025-04-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapcutapp', '0009_remove_contribution_requested_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='year',
            field=models.CharField(default='2024-2025', max_length=9, unique=True),
        ),
    ]
