# Generated by Django 4.1.13 on 2025-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapcutapp', '0010_alter_contribution_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='year',
            field=models.CharField(default='2024-2025', max_length=9),
        ),
    ]
