# Generated by Django 4.1.13 on 2025-05-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asapcutapp', '0011_alter_contribution_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arrears',
        ),
    ]
