# Generated by Django 4.2.13 on 2025-10-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asapcutapp', '0012_delete_arrears'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(default='leader', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_position', to='asapcutapp.position'),
        ),
    ]
