# Generated by Django 4.2.13 on 2025-10-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapcutapp', '0013_alter_userprofile_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('file', models.FileField(upload_to='contribution_excels/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contribution_file',
            },
        ),
    ]
