# Generated by Django 4.2.13 on 2025-10-17 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asapcutapp', '0014_contributionfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='contribution_uploads/')),
                ('year', models.CharField(max_length=9)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contribution_upload',
            },
        ),
        migrations.DeleteModel(
            name='ContributionFile',
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('association', 'year')},
        ),
    ]
