# Generated by Django 4.2.13 on 2025-10-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapcutapp', '0015_contributionupload_delete_contributionfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='payment_date',
            field=models.DateField(default='-'),
        ),
    ]
