# Generated by Django 4.2.13 on 2025-10-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapcutapp', '0017_alter_contribution_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='payment_date',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
